### ISSUE TITLE
How about enlarging Code-Area a bit?

### ISSUE THREAD

**Issue by monkeyotg** [sibbl/fitbit-qrcodes#2]
This is just a suggestion. I think if the Code-Area could be larger, it would be more friendly for the code reading devices to read some complex code.

**Comment by sibbl** [comment]
This is a great idea. While I hardly have problems with complex codes (mostly EU Covid certificates), it might probably be helpful to improve the UI a bit.

There are two things which take up space next to the codes:

1) the scroll indicators: I'd suggest to change them to a 2px border at the top or bottom of the screen. This doesn't follow the design guidelines anymore but I think users of the app will be happy to get some more space.

2) the label/name of the QR code: I'd suggest to hide that space if there's no label, which allows users to save space if they have a single code or know what the 1st, 2nd, 3rd ... code etc is for.

I initially also thought about some interaction with the codes: tapping them to show them fully on the screen. The drawback is, that QR readers need some space around the markers. In tests with multiple QR reader apps on different devices, it showed that they were much faster when there was some white space around. Perhaps I should try again, also with black space around etc.

Also, the screen brightness is a factor. It can currently be cycled through auto/dim/normal/max with the lower right device button. Perhaps this should be part of some tutorial on the first launch, as I don't want to display a distracting on-screen button all the time.

**Comment by Ayn78** [comment]
The readers can recognize the code but I agree, some extra pixels could improve the control speed. I believe the second option should work very well, if no labels or contents are inserted, the QR code could benefit of a larger area.

**Comment by monkeyotg** [comment]
I think if there is an option in the setting to switch on/off the label, that will be quite great.
Let users make their own decisions. For example, for me, I don need labels. Because I can generate QR-Code by myself, that means I can add some elements in my QR-Codes for me to distinguish them.
But other people who don't know how or just don't want, they can let the switch just on.
