### ISSUE TITLE
Code doesn't show up

### ISSUE THREAD

**Issue by edgarssults** [sibbl/fitbit-qrcodes#4]
Hi, I can't get this code to show up. The label is visible, but screen is white. It's on a Versa 2.

![F4051E5D-D612-4905-A78C-A55476E59B96](https://user-images.githubusercontent.com/8101338/137583278-5df60dfa-6369-457c-869a-93870081bace.png)

**Comment by edgarssults** [comment]
It showed up a few days later, not sure why.

![image](https://user-images.githubusercontent.com/8101338/138768111-4e47e943-c45f-49e5-92b3-830bc704e70f.jpg)

**Comment by teresamroberts** [comment]
I’m having this same issue. Fingers crossed that it shows up eventually?

**Comment by sibbl** [comment]
May I ask whether you see other sync issues between your phone and your Fitbit? Some things to check:

1. Does changing the QR code label work immediately or is it also not synced?
2. Is manual syncing of your Fitbit in the Fitbit app successful? 

Unfortunately I have to rely on the connection possibilities Fitbit gives me. I just send the image to the watch. As soon as it's received there, it's displayed. Unfortunately I don't have any insights or control about everything happening in between. 🤔

**Comment by edgarssults** [comment]
> May I ask whether you see other sync issues between your phone and your Fitbit? Some things to check:
> 
> 1. Does changing the QR code label work immediately or is it also not synced?
> 2. Is manual syncing of your Fitbit in the Fitbit app successful?
> 
> Unfortunately I have to rely on the connection possibilities Fitbit gives me. I just send the image to the watch. As soon as it's received there, it's displayed. Unfortunately I don't have any insights or control about everything happening in between. 🤔

Thanks for the reply.
1. Changing the label works immediately.
2. Manual syncing works. My exercises and everything else syncs as expected.
