### ISSUE TITLE
Installazione app

### ISSUE THREAD

**Issue by Gumix68** [sibbl/fitbit-qrcodes#5]
Salve, entrato nella pagina dell'app e confermo l'installazione non accade nulla... Come è possibile risolvere il problema. Il mio è un versa 3

**Comment by sibbl** [comment]
The Fitbit Versa 3 and Fitbit Sense run on Fitbit OS 5 while his app is for Fitbit OS 4 only.

Unfortunately Fitbit decided to not make the devices backwards compatible, so the app might have to be adapted. Please follow #1 for progress when this might be done in the future.
