### ISSUE TITLE
Problema app su Fitbit Versa 2

### ISSUE THREAD

**Issue by cardix97** [sibbl/fitbit-qrcodes#6]
Sul mio Fitbit Versa 2 non mi fa installare l'applicazione perché dice di non essere compatibile.
Ma nella descrizione dell'app c'è scritto compatibile con Versa 2 e vorrei sapere quale è il problema. Grazie

**Comment by sibbl** [comment]
Hi @cardix97, do you have a screenshot for me or some more details? The app should be compatible with Versa 2 since it runs on Fitbit OS 4.

Versa 3 and Sense are the only incompatible devices since they run on Fitbit OS 5.

**Comment by cardix97** [comment]
Hi,
Thanks for the reply.
I send you the screenshot.
I'm Italian and the screenshot are in italian, Sorry, but I think you can
translate.
As you can see from the images, the "INSTALL" button Is disabled and in the
other image it says that the app Is not compatible with my Fitbit device.
Sorry for my english and Thanks for the help.

Il sab 25 dic 2021, 19:35 Sebastian Schubotz ***@***.***> ha
scritto:

**Comment by Chatdhow** [comment]
Hi,
I'm having the same issue here, if more screenshots are needed I can provide !
Thank you for your reactivity !

**Comment by cardix97** [comment]
Risolto dopo un aggiornamento firmware
